hashicorp/terraform-provider-awscc

.goreleaser.yml
=> fix: add prefix to signature file generated by goreleaser

docs/index.md, templates/index.md.tmpl
=> docs: Fix typo in provider name

.github/workflows/release.yml
=> [test]: use the lates `hc-releases` version

go.mod, go.sum, internal/generic/default_value.go, internal/types/duration.go, internal/validate/array.go, internal/validate/required.go, internal/validate/unique_items.go
=> Synch with latest `terraform-plugin-framework`

internal/acctest/testchecks.go, internal/generic/resource.go, internal/generic/translate.go, internal/provider/generators/schema/main.go
=> Remove 'error ' prefix from Errorf returned errors

internal/provider/generators/shared/codegen/emitter.go, internal/validate/uri.go, internal/validate/uri_test.go
=> Add URI validation

docs/data-sources/networkfirewall_firewall_policy.md, docs/data-sources/networkfirewall_rule_group.md, docs/resources/networkfirewall_firewall_policy.md, docs/resources/networkfirewall_rule_group.md, internal/aws/dynamodb/global_table_resource_gen.go, internal/aws/fms/policy_resource_gen.go, internal/aws/fms/policy_singular_data_source_gen.go, internal/aws/networkfirewall/firewall_policy_resource_gen.go, internal/aws/networkfirewall/firewall_policy_singular_data_source_gen.go, internal/aws/networkfirewall/rule_group_resource_gen.go, internal/aws/networkfirewall/rule_group_singular_data_source_gen.go, internal/service/cloudformation/schemas/AWS_DynamoDB_GlobalTable.json, internal/service/cloudformation/schemas/AWS_FMS_Policy.json, internal/service/cloudformation/schemas/AWS_NetworkFirewall_FirewallPolicy.json, internal/service/cloudformation/schemas/AWS_NetworkFirewall_RuleGroup.json, internal/service/cloudformation/schemas/AWS_WAFv2_WebACL.json
=> 02/17/2022 CloudFormation schema refresh

internal/validate/arn.go, internal/validate/array.go, internal/validate/float.go, internal/validate/for_each.go, internal/validate/for_each_test.go, internal/validate/int.go, internal/validate/string.go, internal/validate/time.go, internal/validate/unique_items.go, internal/validate/uri.go
=> Use `plugin-framework` `attr.ValueAs`

.goreleaser.yml
=> Use new `hc-releases`

internal/provider/generators/resource/main.go
=> Use `%q` when generating schema description

docs/data-sources/mediapackage_packaging_configuration.md, docs/resources/mediapackage_packaging_configuration.md, internal/aws/mediapackage/packaging_configuration_resource_gen.go, internal/aws/mediapackage/packaging_configuration_singular_data_source_gen.go, internal/provider/generators/allschemas/available_schemas.2022-04-27.hcl, internal/service/cloudformation/schemas/AWS_MediaPackage_PackagingConfiguration.json
=> 04/27/2022 CloudFormation schema refresh

README.md
=> Correct Terraform logo link

main.go
=> Add `-debug` command-line flag

go.mod, go.sum, internal/provider/generators/shared/codegen/emitter.go
=> CloudFormation resource schema `Property.Maximum` and `Property.Minimum` are `json.Number`

docs/index.md, templates/index.md.tmpl
=> Adds required version note to top of index.

internal/service/cloudformation/schemas/AWS_EC2_TransitGatewayPeeringAttachment.json
=> Latest CFN schema for `AWS::EC2::TransitGatewayPeeringAttachment`

.copywrite.hcl, contributing/CONTRIBUTING.md, contributing/add-examples-to-documentation.md
=> Add contributor guide to explain how to add examples

.github/dependabot.yml
=> Group AWS SDK for Go `dependabot` updates

.github/dependabot.yml
=> Group all AWS for Go v2 `dependabot` updates

.github/workflows/release.yml
=> Revert `actions/upload-artifact@4.0.0`

internal/generic/plural_data_source.go, internal/generic/resource.go, internal/generic/singular_data_source.go, internal/provider/provider.go, internal/service/cloudcontrol/provider.go
=> Ensure AWS SDK for Go v2 HTTP requests and responses are logged

.github/workflows/release.yml
=> GHA `Release` workflow: Upgrade to `hashicorp/ghaction-terraform-provider-release@v3`

internal/provider/generators/common/generator.go, internal/provider/generators/import-examples/main.go, internal/provider/generators/plural-data-source/main.go, internal/provider/generators/resource/main.go, internal/provider/generators/schema/main.go, internal/provider/generators/shared/generator.go, internal/provider/generators/shared/template_data.go, internal/provider/generators/singular-data-source/main.go
=> `internal/provider/generators`: Align with `terraform-provider-aws`

.github/dependabot.yml
=> `protobuf` should only be updated via `terraform-plugin-go`/`terraform-plugin-framework`

docs/resources/sns_topic.md, examples/resources/awscc_sns_topic/sns_topic.tf, examples/resources/awscc_sns_topic/sns_topic_fifo.tf
=> docs: fix example for awscc_sns_topic

docs/resources/ec2_internet_gateway.md, examples/resources/awscc_ec2_internet_gateway/ec2_internet_gateway.tf
=> docs: update example for awscc_ec2_internet_gateway

docs/resources/sns_topic_inline_policy.md, examples/resources/awscc_sns_topic_inline_policy/sns_topic_inline_policy.tf, templates/resources/sns_topic_inline_policy.md.tmpl
=> docs: updated examples for sns_topic_inline_policy

.goreleaser.yml
Modify .goreleaser to include license file in release package.
=> Include license file in release package

contributing/DEVELOPMENT.md, go.mod, tools/go.mod
=> Build with Go 1.22

docs/resources/cloudtrail_trail.md, examples/resources/awscc_cloudtrail_trail/complex_trail.tf
=> docs: update example for awscc_cloudtrail_trail event selectors

go.mod, tools/go.mod
=> Build with Go 1.22.2

README.md, contributing/FAQ.md, docs/guides/using-aws-with-awscc-provider.md, docs/index.md, templates/index.md.tmpl
=> Add things to know section and remove tp verbiage

CHANGELOG.md
=> update CHANGELOG release version

.github/workflows/labelers.yml
=> Fix errant double parenthesis

docs/index.md, templates/index.md.tmpl
=> docs: bump version in example

CODEOWNERS
@hashicorp/terraform-aws Team for all content, @breathingdust and @justinretzolk for github actions.
=> Add a codeowners file

go.mod, tools/go.mod
=> Go v1.22.4

go.mod, tools/go.mod
=> Go v1.22.5

docs/resources/xray_sampling_rule.md, examples/resources/awscc_xray_sampling_rule/xray_sampling_rule.tf
=> docs: update notes on awscc_xray_sampling_rule

go.mod, tools/go.mod
=> Go v1.22.6

.github/actions/community_check/README.md, .github/actions/team_working_board/README.md, .github/actions/team_working_board/action.yml
=> Add working board composite action

CHANGELOG.md
=>  Update CHANGELOG.md after v1.13.0

.github/workflows/release.yml
=> [GHA] Use app token for new changelog version step

.github/workflows/label-notifications.yml, .github/workflows/pull_request_feed.yml, .github/workflows/release-tag.yml
Replicates internal feed notifications present in the AWS provider.
=> Add team feed integration for AWSCC

.github/workflows/feed-approval.yml
=> [Internal] Adds maintainer approval to feed

.github/workflows/feed-comments.yml
=> [Internal] Feed - Notify on maintainer comment

.github/workflows/feed-approval.yml
=> [Internal] Fixes for approval feed integration

CHANGELOG.md
=> add CHANGELOG entry for #2022

META.d/_summary.yaml
=> [chore] Add META.d folder to repository

CHANGELOG.md
=> Add new resources & data sources to correct CHANGELOG section

CHANGELOG.md
=> format CHANGELOG

docs/resources/qbusiness_data_source.md, examples/resources/awscc_qbusiness_data_source/qbusiness_data_source.tf, examples/resources/awscc_qbusiness_data_source/qbusiness_data_source_webcrawl.tf, templates/resources/qbusiness_data_source.md.tmpl
=> docs: improve qbusiness datasource for webcrawler

.github/workflows/build.yml, .release/ci.hcl
=> correct spelling

.github/workflows/provider-release.yml
=> add workflow to trigger releases

.github/PULL_REQUEST_TEMPLATE.md
=> Update PR template to include PCI verbiage

.github/workflows/registry-check.yml
=> Add name to registry-check workflow and adjust Slack Channel settings

.github/workflows/update-changelog.yml
=> actions: add script to create change update PR

.github/workflows/post-promote-production.yml, .github/workflows/update-changelog.yml
=> actions: update changelog pr post release

go.mod, go.sum, internal/provider/generators/import-examples/main.go, internal/provider/generators/schema/imports.tmpl, internal/provider/import_examples_gen.json
=> refactor import example cli

internal/update/changelog.go, internal/update/changelog_test.go, internal/update/github.go, internal/update/hcl_parser.go, internal/update/hcl_parser_test.go, internal/update/main.go, internal/update/makes.go
=> features/copyright + HCL trimming 
