.goreleaser.yml
=> fix: add dearmor flag to signore sign command

README.md
Hello maintainers 👋🏼 
The Discuss link was pointing to the subforum for the `-aws` provider; I've updated this to point to the new subforum (ID: 58)
Happy Doctober!
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted …
=> corrects link to Discuss subforum

internal/provider/generators/import-examples/main.go
=> Fix generators/import-examples from failing w/ too many open files

.goreleaser.yml
=> goreleaser: add "plain" signature file creation

.github/workflows/pre-release.yml, .github/workflows/release.yml
=> GithubActions: create tag workflow

.github/workflows/release.yml, .goreleaser.yml
=> Update release workflow for goreleaser extra_files remap support and remove other protocol handling

internal/diag/diag.go, internal/diags/diags.go, internal/generic/default_value.go, internal/validate/arn.go, internal/validate/array.go, internal/validate/float.go, internal/validate/for_each.go, internal/validate/for_each_test.go, internal/validate/int.go, internal/validate/meta_test.go, internal/validate/required.go, internal/validate/string.go, internal/validate/time.go, internal/validate/unique_items.go
There's a lot of repetition in our `diag.Diagnostic` errors, and they're free-form instead of using pre-defined constants, etc. This PR packages many of the repeated Diagnostics
=> Encapsulating `diag.Diagnostic`s

.goreleaser.yml, CHANGELOG.md
=> Don't exclude `darwin/arm64` builds from `goreleaser`

.github/ISSUE_TEMPLATE/Bug_Report.md, .github/ISSUE_TEMPLATE/Feature_Request.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, contributing/FAQ.md
This pull request fixes a few small things:
* broken link to contributing page
* broken url to Terraform logo
* broken Markdown for link to AWS CloudFormation public roadmap
* spelling for CloudFormation
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying …
=> Improve readme and pull request template

.github/workflows/release.yml, .goreleaser.yml
Reference: https://github.com/hashicorp/ghaction-terraform-provider-release
The reusable workflow should remove some of the management burden of the HashiCorp Terraform provider release process.
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema …
=> Update release workflow to use hashicorp/ghaction-terraform-provider-release

internal/generic/multiset_test.go
=> Add Multiset test for list of objects

CHANGELOG.md, internal/generic/resource.go, internal/generic/unknown.go, internal/generic/unknown_test.go
=> Improve setting of Unknown values in State after Create/Update to support "complex types"

.github/dependabot.yml, go.mod, internal/acctest/testchecks.go, internal/generic/logging.go, internal/generic/plural_data_source.go, internal/generic/resource.go, internal/generic/singular_data_source.go, internal/generic/translate.go, internal/provider/provider.go, internal/service/cloudcontrol/delete.go, internal/service/cloudcontrol/find.go, internal/service/cloudcontrol/list.go
This reverts commit 66db1b0bac1e41ba7d7940e8f54d603f66bc1ade.
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing …
=> Restore use of `tflog`

CHANGELOG.md, internal/generic/translate.go, internal/generic/translate_test.go
Empty lists returned by the provider were causing errors on any subsequent state refresh. The state stored a `null` value, whereas the generated plan would return an empty `tftypes.List`. This would cause Terraform to fail with an error like
```
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hashicorp/awscc" planned an invalid value for awscc_ec2_vpc.test.tags: planned value
│ cty.ListValEmpty(cty.Object(map[string]cty.Type{"key":cty.String, "value":cty.String})) for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
This PR short-circuits the empty list case to return a `null` value of the list type instead of an empty list. This allows Terraform to continue and encounter behaviour …
=> Return `null` instead of an empty `tftypes.List` when the list is empty

.goreleaser.yml
=> goreleaser: Comment out` publishers` `extra_files` to prevent runtime error

.github/workflows/release.yml
=> .github/workflows/release: restore workflow trigger to tag push

CHANGELOG.md, internal/aws/ec2/vpc_resource_test.go, internal/service/cloudcontrol/waiter.go
=> Prevent infinite loop if an API error is returned when waiting for an async operation to complete

internal/generic/jsonstring.go, internal/generic/jsonstring_test.go
=> Add `AttributePlanModifier` that suppresses semantically insignificant differences between JSON strings

.github/goreleaser-cross-compiler-test.yml, .github/workflows/goreleaser-ci.yml
=> 32-bit `goreleaser` build for CI

internal/validate/int.go, internal/validate/int_test.go
=> Use `int64` in Int validators

internal/generic/jsonstring.go, internal/generic/jsonstring_test.go
=> Handle `null` current value when planning JSON strings

.github/dependabot.yml
=> Increase dependabot open PR limit from 5 to 30 for `go.mod`

.goreleaser.yml
=> Release: Set provider version in HTTP User-Agent strings

.golangci.yml, GNUmakefile, internal/generic/translate.go, internal/naming/naming.go, internal/provider/generators/import-examples/main.go, internal/provider/generators/plural-data-source/main.go, internal/provider/generators/resource/main.go, internal/provider/generators/schema/main.go, internal/provider/generators/singular-data-source/main.go, internal/validate/int.go, internal/validate/required.go, tools/go.mod
=> Cleanup after go1.19 upgrade

contributing/pullrequest-submission-and-lifecycle.md
=> Fix `markdown-link-check` errors

.github/dependabot.yml
=> Include `github.com/aws/smithy-go` module in `aws-sdk-go` dependabot group

.teamcity/scripts/configure_goenv.sh
=> configure from gomod if config is missing

docs/resources/s3_bucket.md, examples/resources/awscc_s3_bucket/s3_bucket_encryption.tf, templates/resources/s3_bucket.md.tmpl
=> docs: awscc_s3_bucket - default encryption

docs/resources/ec2_vpc.md, examples/resources/awscc_ec2_vpc/ec2_vpc_ipam.tf, examples/resources/awscc_ec2_vpc/ec2_vpc_ipv6.tf, templates/resources/ec2_vpc.md.tmpl
=> docs: added example for ec2_vpc ipv6

infrastructure/repository/labels-workflow.tf
=> Add `partner` and `external-maintainer` labels

.github/workflows/labelers.yml
=> Fix labeler workflow by specifying GitHub token

CHANGELOG.md, internal/provider/provider.go, internal/types/duration.go, internal/types/duration_test.go
=> Fix `panic: Go Duration ValueDuration Error`

.github/actions/community_check/README.md, .github/actions/community_check/action.yml, .github/workflows/labelers.yml
=> Update community check to Composite Action

.github/actions/community_check/action.yml
=> Fix community check

.github/ISSUE_TEMPLATE/Bug_Report.md
=> Add `bug` label to bug report template

docs/resources/amplify_domain.md, examples/resources/awscc_amplify_domain/amplify_domain.tf
=> fix: updated example for awscc_amplify_domain

templates/guides/using-aws-with-awscc-provider.md.tmpl
=> fix: added guides under templates

GNUmakefile
=> split make targets for docs generation

.github/workflows/projects.yml
=> Introduce workflow to automate GitHub Projects

.github/workflows/regressions.yml
=> Add workflow to handle regressions

CODEOWNERS
=> Add team as GitHub workflow owners

docs/resources/sagemaker_cluster.md, examples/resources/awscc_sagemaker_cluster/sagemaker_cluster_eks.tf
=> fix: reference path in example awscc_sagemaker_cluster

.github/goreleaser-cross-compiler-test.yml, .goreleaser.yml
=> [chore] Update for goreleaser deprecations

CHANGELOG.md, docs/index.md, internal/provider/provider.go
The PR #2029 introduced a breaking change with the `assume_role` attribute. This PR rolls back the breaking change and removes the ability to do IAM role chaining. This will be reintroduced in a future version.
Closes #2041
=> provider: Revert breaking change from IAM role chaining

GNUmakefile
Provides descriptions of the available targets, similar to the implementation in the main AWS provider.
```console
% make help
all                   Generate all schemas, resources, data sources, documentation, and build the provider
build                 Build the provider
docs-all              Generate all documentation
docs-import           Generate import documentation
docs                  Generate documentation
golangci-lint         Run golangci-lint
help                  Display this help
importlint            Run importlint
lint                  Run all linters
plural-data-sources   Generate plural data sources
resources             Generate resources
schemas               Generate schemas
singular-data-sources Generate singular data sources
test                  Run unit tests …
```
=> chore: add help make target

.goreleaser.yml
Before:
```console
% goreleaser check
• checking                                 path=.goreleaser.yml
• DEPRECATED:  archives.format  should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
• .goreleaser.yml                                  error=configuration is valid, but uses deprecated properties
⨯ command failed                                   error=1 out of 1 configuration file(s) have issues
```
After:
```console
% goreleaser check
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using GoReleaser!
```
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41094
=> ci: fix goreleaser deprecation warning

internal/service/cloudcontrol/list.go
=> fix: pagination on plural datasources

.github/workflows/post-promote-production.yml, .github/workflows/registry-check.yml, .release/ci.hcl
=> Add post-promote-production workflow

.github/workflows/crt-post-promote-production.yml, .release/ci.hcl
=> Prepend `post-promote-production` with `crt-`
